import { IResolvedSnippet } from "./types";

const JS_TS_LANG_IDS = [
  "javascript",
  "typescript",
  "javascriptreact",
  "typescriptreact",
];
const REACT_LANG_IDS = ["javascriptreact", "typescriptreact"];
const PYTHON_LANG_IDS = ["python"];
const GO_LANG_IDS = ["go"];

/** Built-in snippets keyed by their original command key (e.g. "if" -> "surround.with.if") */
export const builtinSnippets: Record<string, IResolvedSnippet> = {
  if: {
    label: "if",
    description: "if ($condition) { ... }",
    snippet: "if(${1:condition}) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "if",
    _source: "builtin",
    _key: "if",
  },
  ifElse: {
    label: "if/else",
    description: "if ($condition) { ... } else { $else }",
    snippet:
      "if(${1:condition}) {\n\t$TM_SELECTED_TEXT\n} else {\n\t$2\n}$0",
    commandName: "ifElse",
    _source: "builtin",
    _key: "ifElse",
  },
  tryCatch: {
    label: "try/catch",
    description: "try { ... } catch (err) { $catchBlock }",
    snippet:
      "try {\n\t$TM_SELECTED_TEXT\n} catch (err) {\n\t$1\n}$0",
    commandName: "tryCatch",
    _source: "builtin",
    _key: "tryCatch",
  },
  tryFinally: {
    label: "try/finally",
    description: "try { ... } finally { $finalBlock }",
    snippet: "try {\n\t$TM_SELECTED_TEXT\n} finally {\n\t$1\n}$0",
    commandName: "tryFinally",
    _source: "builtin",
    _key: "tryFinally",
  },
  tryCatchFinally: {
    label: "try/catch/finally",
    description:
      "try { ... } catch (err) {$catchBlock} finally { $finalBlock }",
    snippet:
      "try {\n\t$TM_SELECTED_TEXT\n} catch (err) {\n\t$1\n} finally {\n\t$2\n}$0",
    commandName: "tryCatchFinally",
    _source: "builtin",
    _key: "tryCatchFinally",
  },
  for: {
    label: "for",
    description: "for ($1) { ... }",
    snippet: "for ($1) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "for",
    _source: "builtin",
    _key: "for",
  },
  fori: {
    label: "fori",
    description: "for (let i = 0; ... ; i = i + 1) { ... }",
    snippet:
      "for (let ${1:i} = ${2:0}; ${3:conditions}; $1 = $1 + 1) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "fori",
    _source: "builtin",
    _key: "fori",
  },
  forEach: {
    label: "forEach",
    description: "items.forEach((item) => { ... })",
    snippet:
      "${1:items}.forEach((${2:item}) => {\n\t$TM_SELECTED_TEXT\n})$0",
    commandName: "forEach",
    _source: "builtin",
    _key: "forEach",
  },
  forEachAsync: {
    label: "forEachAsync",
    description: "items.forEach(async (item) => { ... })",
    snippet:
      "${1:items}.forEach(async (${2:item}) => {\n\t$TM_SELECTED_TEXT\n})$0",
    commandName: "forEachAsync",
    _source: "builtin",
    _key: "forEachAsync",
  },
  forEachFn: {
    label: "forEachFn",
    description: "items.forEach(function (item) { ... })",
    snippet:
      "${1:items}.forEach(function (${2:item}) {\n\t$TM_SELECTED_TEXT\n})$0",
    commandName: "forEachFn",
    _source: "builtin",
    _key: "forEachFn",
  },
  forEachAsyncFn: {
    label: "forEachAsyncFn",
    description: "items.forEach(async function (item) { ... })",
    snippet:
      "${1:items}.forEach(async function (${2:item}) {\n\t$TM_SELECTED_TEXT\n})$0",
    commandName: "forEachAsyncFn",
    _source: "builtin",
    _key: "forEachAsyncFn",
  },
  arrowFunction: {
    label: "arrowFunction",
    description: "const $name = ($params) => { ... }",
    snippet:
      "const ${1:fnName} = (${2:params}) => {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "arrowFunction",
    _source: "builtin",
    _key: "arrowFunction",
  },
  asyncArrowFunction: {
    label: "asyncArrowFunction",
    description: "const $name = async ($params) => { ... }",
    snippet:
      "const ${1:fnName} = async (${2:params}) => {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "asyncArrowFunction",
    _source: "builtin",
    _key: "asyncArrowFunction",
  },
  functionDeclaration: {
    label: "functionDeclaration",
    description: "function $name ($params) { ... }",
    snippet:
      "function ${1:name} (${2:params}) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "functionDeclaration",
    _source: "builtin",
    _key: "functionDeclaration",
  },
  asyncFunctionDeclaration: {
    label: "asyncFunctionDeclaration",
    description: "async function $name ($params) { ... }",
    snippet:
      "async function ${1:name} (${2:params}) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "asyncFunctionDeclaration",
    _source: "builtin",
    _key: "asyncFunctionDeclaration",
  },
  functionExpression: {
    label: "functionExpression",
    description: "const $name = function ($params) { ... }",
    snippet:
      "const ${1:name} = function (${2:params}) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "functionExpression",
    _source: "builtin",
    _key: "functionExpression",
  },
  asyncFunctionExpression: {
    label: "asyncFunctionExpression",
    description: "const $name = async function ($params) { ... }",
    snippet:
      "const ${1:name} = async function (${2:params}) {\n\t$TM_SELECTED_TEXT\n}$0",
    commandName: "asyncFunctionExpression",
    _source: "builtin",
    _key: "asyncFunctionExpression",
  },
  iife: {
    label: "IIFE",
    description: "(function $name($params){ ... })($arguments);",
    snippet:
      "(function ${1:name}(${2:params}){\n\t$TM_SELECTED_TEXT\n})(${3:arguments});$0",
    commandName: "iife",
    _source: "builtin",
    _key: "iife",
  },
  element: {
    label: "<element></element>",
    description: "<element>...</element>",
    snippet: "<${1}$2>$TM_SELECTED_TEXT</$1>$0",
    languageIds: ["html", "typescriptreact", "javascriptreact", "jsx", "markdown"],
    commandName: "element",
    _source: "builtin",
    _key: "element",
  },
  comment: {
    label: "comment",
    description: "/** ...  */",
    snippet: "/**\n\t$TM_SELECTED_TEXT\n*/$0",
    commandName: "comment",
    _source: "builtin",
    _key: "comment",
  },
  region: {
    label: "#region",
    description: "#region $regionName ... #endregion",
    snippet: "// #region ${1:regionName}\n$TM_SELECTED_TEXT\n// #endregion$0",
    commandName: "region",
    _source: "builtin",
    _key: "region",
  },
  templateLiteral: {
    label: "Template Literal",
    description: "`...` (Also replaces single and double quotes with backtick)",
    snippet: "`${TM_SELECTED_TEXT/['\"](.*?)['\"]/$1/g}`$0",
    commandName: "templateLiteral",
    _source: "builtin",
    _key: "templateLiteral",
  },
  templateLiteralVariable: {
    label: "Template Literal Variable",
    description:
      "`${...}` (Also replaces single and double quotes with backtick)",
    snippet:
      "`$1\\${${TM_SELECTED_TEXT/['\"](.*?)['\"]/$1/g}}$2`$0",
    commandName: "templateLiteralVariable",
    _source: "builtin",
    _key: "templateLiteralVariable",
  },

  // ── JS/TS snippets ──────────────────────────────────────────────────

  consoleLog: {
    label: "console.log",
    description: "console.log(...)",
    snippet: "console.log($TM_SELECTED_TEXT)$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "consoleLog",
    _source: "builtin",
    _key: "consoleLog",
  },
  consoleError: {
    label: "console.error",
    description: "console.error(...)",
    snippet: "console.error($TM_SELECTED_TEXT)$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "consoleError",
    _source: "builtin",
    _key: "consoleError",
  },
  promiseWrapper: {
    label: "Promise",
    description: "new Promise((resolve, reject) => { ... })",
    snippet:
      "new Promise((${1:resolve}, ${2:reject}) => {\n\t$TM_SELECTED_TEXT\n})$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "promiseWrapper",
    _source: "builtin",
    _key: "promiseWrapper",
  },
  setTimeoutSnippet: {
    label: "setTimeout",
    description: "setTimeout(() => { ... }, delay)",
    snippet: "setTimeout(() => {\n\t$TM_SELECTED_TEXT\n}, ${1:delay})$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "setTimeoutSnippet",
    _source: "builtin",
    _key: "setTimeoutSnippet",
  },
  setIntervalSnippet: {
    label: "setInterval",
    description: "setInterval(() => { ... }, delay)",
    snippet: "setInterval(() => {\n\t$TM_SELECTED_TEXT\n}, ${1:delay})$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "setIntervalSnippet",
    _source: "builtin",
    _key: "setIntervalSnippet",
  },
  jsonStringify: {
    label: "JSON.stringify",
    description: "JSON.stringify(...)",
    snippet: "JSON.stringify($TM_SELECTED_TEXT)$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "jsonStringify",
    _source: "builtin",
    _key: "jsonStringify",
  },
  jsonParse: {
    label: "JSON.parse",
    description: "JSON.parse(...)",
    snippet: "JSON.parse($TM_SELECTED_TEXT)$0",
    languageIds: JS_TS_LANG_IDS,
    commandName: "jsonParse",
    _source: "builtin",
    _key: "jsonParse",
  },
  typeofCheck: {
    label: "typeof",
    description: 'typeof ... === "type"',
    snippet: 'typeof $TM_SELECTED_TEXT === "${1:string}"$0',
    languageIds: JS_TS_LANG_IDS,
    commandName: "typeofCheck",
    _source: "builtin",
    _key: "typeofCheck",
  },

  // ── React snippets ──────────────────────────────────────────────────

  reactFragment: {
    label: "<>Fragment</>",
    description: "<>...</>",
    snippet: "<>\n\t$TM_SELECTED_TEXT\n</>$0",
    languageIds: REACT_LANG_IDS,
    commandName: "reactFragment",
    _source: "builtin",
    _key: "reactFragment",
  },
  reactSuspense: {
    label: "<Suspense>",
    description: "<Suspense fallback={...}>...</Suspense>",
    snippet:
      "<Suspense fallback={${1:<Loading />}}>\n\t$TM_SELECTED_TEXT\n</Suspense>$0",
    languageIds: REACT_LANG_IDS,
    commandName: "reactSuspense",
    _source: "builtin",
    _key: "reactSuspense",
  },
  reactConditional: {
    label: "{condition && ...}",
    description: "{condition && (...)}",
    snippet: "{${1:condition} && (\n\t$TM_SELECTED_TEXT\n)}$0",
    languageIds: REACT_LANG_IDS,
    commandName: "reactConditional",
    _source: "builtin",
    _key: "reactConditional",
  },
  reactTernary: {
    label: "{condition ? ... : ...}",
    description: "{condition ? (...) : (...)}",
    snippet: "{${1:condition} ? (\n\t$TM_SELECTED_TEXT\n) : (\n\t$2\n)}$0",
    languageIds: REACT_LANG_IDS,
    commandName: "reactTernary",
    _source: "builtin",
    _key: "reactTernary",
  },
  reactMap: {
    label: "{items.map(...)}",
    description: "{items.map((item) => (...))}",
    snippet:
      "{${1:items}.map((${2:item}) => (\n\t$TM_SELECTED_TEXT\n))}$0",
    languageIds: REACT_LANG_IDS,
    commandName: "reactMap",
    _source: "builtin",
    _key: "reactMap",
  },

  // ── Python snippets ─────────────────────────────────────────────────

  pyTryExcept: {
    label: "try/except",
    description: "try: ... except Exception:",
    snippet:
      "try:\n\t$TM_SELECTED_TEXT\nexcept ${1:Exception} as ${2:e}:\n\t${3:raise}$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyTryExcept",
    _source: "builtin",
    _key: "pyTryExcept",
  },
  pyTryExceptFinally: {
    label: "try/except/finally",
    description: "try: ... except: ... finally:",
    snippet:
      "try:\n\t$TM_SELECTED_TEXT\nexcept ${1:Exception} as ${2:e}:\n\t${3:raise}\nfinally:\n\t$4$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyTryExceptFinally",
    _source: "builtin",
    _key: "pyTryExceptFinally",
  },
  pyWith: {
    label: "with",
    description: "with ctx_manager as var: ...",
    snippet: "with ${1:context_manager} as ${2:var}:\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyWith",
    _source: "builtin",
    _key: "pyWith",
  },
  pyDef: {
    label: "def",
    description: "def name(params): ...",
    snippet: "def ${1:name}(${2:params}):\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyDef",
    _source: "builtin",
    _key: "pyDef",
  },
  pyAsyncDef: {
    label: "async def",
    description: "async def name(params): ...",
    snippet: "async def ${1:name}(${2:params}):\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyAsyncDef",
    _source: "builtin",
    _key: "pyAsyncDef",
  },
  pyClass: {
    label: "class",
    description: "class Name: ...",
    snippet: "class ${1:Name}${2:(${3:object})}:\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyClass",
    _source: "builtin",
    _key: "pyClass",
  },
  pyFor: {
    label: "for/in",
    description: "for item in iterable: ...",
    snippet: "for ${1:item} in ${2:iterable}:\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyFor",
    _source: "builtin",
    _key: "pyFor",
  },
  pyWhile: {
    label: "while",
    description: "while condition: ...",
    snippet: "while ${1:condition}:\n\t$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyWhile",
    _source: "builtin",
    _key: "pyWhile",
  },
  pyIf: {
    label: "if/elif/else",
    description: "if: ... elif: ... else:",
    snippet:
      "if ${1:condition}:\n\t$TM_SELECTED_TEXT\nelif ${2:condition}:\n\t$3\nelse:\n\t$4$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyIf",
    _source: "builtin",
    _key: "pyIf",
  },
  pyIfMain: {
    label: 'if __name__ == "__main__"',
    description: 'if __name__ == "__main__": ...',
    snippet: 'if __name__ == "__main__":\n\t$TM_SELECTED_TEXT$0',
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyIfMain",
    _source: "builtin",
    _key: "pyIfMain",
  },
  pyDecorator: {
    label: "@decorator",
    description: "@decorator ...",
    snippet: "@${1:decorator}\n$TM_SELECTED_TEXT$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyDecorator",
    _source: "builtin",
    _key: "pyDecorator",
  },
  pyListComp: {
    label: "list comprehension",
    description: "[expr for item in ...]",
    snippet: "[${1:$TM_SELECTED_TEXT} for ${2:item} in ${3:iterable}]$0",
    languageIds: PYTHON_LANG_IDS,
    commandName: "pyListComp",
    _source: "builtin",
    _key: "pyListComp",
  },

  // ── Go snippets ─────────────────────────────────────────────────────

  goIfErr: {
    label: "if err != nil",
    description: "if err != nil { ... }",
    snippet: "if err != nil {\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goIfErr",
    _source: "builtin",
    _key: "goIfErr",
  },
  goFor: {
    label: "Go for",
    description: "for condition { ... }",
    snippet: "for ${1:condition} {\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goFor",
    _source: "builtin",
    _key: "goFor",
  },
  goForRange: {
    label: "for range",
    description: "for i, v := range slice { ... }",
    snippet:
      "for ${1:i}, ${2:v} := range ${3:slice} {\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goForRange",
    _source: "builtin",
    _key: "goForRange",
  },
  goFunc: {
    label: "func",
    description: "func name(params) returnType { ... }",
    snippet: "func ${1:name}(${2:params}) ${3:error} {\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goFunc",
    _source: "builtin",
    _key: "goFunc",
  },
  goGoroutine: {
    label: "goroutine",
    description: "go func() { ... }()",
    snippet: "go func() {\n\t$TM_SELECTED_TEXT\n}()$0",
    languageIds: GO_LANG_IDS,
    commandName: "goGoroutine",
    _source: "builtin",
    _key: "goGoroutine",
  },
  goDefer: {
    label: "defer",
    description: "defer func() { ... }()",
    snippet: "defer func() {\n\t$TM_SELECTED_TEXT\n}()$0",
    languageIds: GO_LANG_IDS,
    commandName: "goDefer",
    _source: "builtin",
    _key: "goDefer",
  },
  goSelect: {
    label: "select",
    description: "select { case ...: ... }",
    snippet: "select {\ncase ${1:ch}:\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goSelect",
    _source: "builtin",
    _key: "goSelect",
  },
  goSwitch: {
    label: "switch",
    description: "switch expr { case ...: ... }",
    snippet:
      "switch ${1:expr} {\ncase ${2:value}:\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goSwitch",
    _source: "builtin",
    _key: "goSwitch",
  },
  goIfElse: {
    label: "Go if/else",
    description: "if condition { ... } else { ... }",
    snippet:
      "if ${1:condition} {\n\t$TM_SELECTED_TEXT\n} else {\n\t$2\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goIfElse",
    _source: "builtin",
    _key: "goIfElse",
  },
  goMethod: {
    label: "method",
    description: "func (r Receiver) name() { ... }",
    snippet:
      "func (${1:r} ${2:Receiver}) ${3:name}(${4:params}) ${5:error} {\n\t$TM_SELECTED_TEXT\n}$0",
    languageIds: GO_LANG_IDS,
    commandName: "goMethod",
    _source: "builtin",
    _key: "goMethod",
  },
  goMutex: {
    label: "mutex lock/unlock",
    description: "mu.Lock() ... defer mu.Unlock()",
    snippet: "${1:mu}.Lock()\ndefer $1.Unlock()\n$TM_SELECTED_TEXT$0",
    languageIds: GO_LANG_IDS,
    commandName: "goMutex",
    _source: "builtin",
    _key: "goMutex",
  },
};
